name: fish-phantom
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.19.5
  - pandas=1.1.5
  - requests=2.25.1
  - beautifulsoup4=4.9.3
  - lxml=4.6.5
  - tqdm=4.64.1
  - colorama=0.4.5
  - cryptography=3.4.8
  - networkx=2.6.3
  - asn1crypto=1.4.0
  - pip
  - pip:
      - scikit-learn==1.1.3
      - googlesearch-python==1.0.1
      - whois==0.9.13
      - gunicorn==20.1.0
      - python-magic==0.4.27
      - androguard==3.3.5
